### ISSUE TITLE
Feature request: Highlight erroneous lines in red

### ISSUE THREAD

**Issue by UnrealApex** [jslint-org/jslint#374]
It would be nice if JSLint highlighted erroneous lines/lines of interest in red(or yellow) like in CSSLint:
![image](https://user-images.githubusercontent.com/79121360/141610107-0b6e410b-175b-45ec-897d-5911fc7744d4.png)

**Comment by kaizhu256** [comment]
closing this as won't fix for following reason:

- this feature seems most prevalent in read-only reports (like csslint's), rather than text-editors.
- text-editors seem to generally mark errors 
    - inplace where it occurs
    - on the left-gutter

![image](https://user-images.githubusercontent.com/280571/153721778-9bcd4704-8deb-48f6-bee8-0c82d86c6cd5.png)
